### PR TITLE
Fix resolving of relative `sourceMappingURL`

### PR DESCRIPTION
**Pull request by evanweible-wf**
Proposed fix for #2

### CODE REVIEW

**Review by aegilops — APPROVED** [review]
I'm approving this, but I'd love to also have some test cases to confirm that this behaviour is correct, since I haven't tested it for myself.

If you'd be able to share a minimal repo that shows the problem that it is fixing that'd be great, but I'm not going to make it a blocker to accepting the change for you.

**Comment by aegilops** [comment]
If you're ready to take this out of "draft" then I'm happy to merge it, and tag it as v1.1

**Comment by aegilops** [comment]
I've merged https://github.com/advanced-security/remap-sarif/pull/4 which I wrote to resolve this, based on some local testing, which I saw before your comment here.

Can you try it out to see if it fixes things please?

I'm happy to target some new work to relocate `codeFlows` and `relatedLocations` as well.

**Comment by evanweible-wf** [comment]
Just gave it a shot and it looks like it's closer - it does run successfully now, but I'm seeing errors like this:
```
WARNING:__main__:Index error: ('Mapping error: %s', FileNotFoundError(2, 'No such file or directory'))
```
And unfortunately it doesn't actually print the file path so I can't do much with that. Additionally, the findings reported to "Code scanning alerts" view are still un-source-mapped.

**Comment by evanweible-wf** [comment]
@aegilops One thing that I find odd is that I have to configure the `sourceroot` to be the output directory of the build in order for it to run succesfully, but I can't see how it would then find the original source files when applying the source maps. Seems like I need to be able to configure two different paths - one for the source files and one for build directory. Does that make sense or am I missing something?

**Comment by aegilops** [comment]
Thanks for reporting the extra problem. Can you raise them it as an issue please?

I'm going to close this PR, since I think that my changes make this outdated, and it's best to continue from the new baseline

**Pull request closed without merging**
